replaced with explicit error handling

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -38,6 +38,9 @@ jobs:
               run: npm ci
             - name: Run Tests
               run: |
-                set -e 
                 slitherin tests/ --separated
+                if [ $? -ne 0 ]; then
+                  echo "Tests failed!"
+                  exit 1
+                fi
             
